// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'pt'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * A​p​l​i​c​a​t​i​o​n​ ​t​i​t​l​e
		 */
		title: string
		/**
		 * E​x​a​m​p​l​e​ ​a​p​p​ ​w​i​t​h​ ​i​1​8​n​ ​s​u​p​p​o​r​t
		 */
		description: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
	}
	nav: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * P​r​o​j​e​c​t​s
		 */
		projects: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * U​s​e​r​ ​m​e​n​u
		 */
		userMenu: string
	}
	auth: {
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		loginWithGoogle: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		logout: string
		/**
		 * C​u​r​r​e​n​t​ ​u​s​e​r​:​ ​{​u​s​e​r​}
		 * @param {string} user
		 */
		currentUser: RequiredParams<'user'>
		/**
		 * S​i​g​n​ ​o​u​t​ ​f​r​o​m​ ​a​c​c​o​u​n​t
		 */
		signOut: string
	}
	projects: {
		/**
		 * M​y​ ​P​r​o​j​e​c​t​s
		 */
		title: string
		/**
		 * {​c​o​u​n​t​}​ ​p​r​o​j​e​c​t​s
		 * @param {unknown} count
		 */
		count: RequiredParams<'count'>
		empty: {
			/**
			 * Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​p​r​o​j​e​c​t​s​ ​y​e​t
			 */
			title: string
			/**
			 * C​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​p​r​o​j​e​c​t​ ​t​o​ ​w​o​r​k​ ​w​i​t​h​ ​i​c​o​n​s
			 */
			description: string
			/**
			 * C​r​e​a​t​e​ ​f​i​r​s​t​ ​p​r​o​j​e​c​t
			 */
			createFirst: string
		}
		/**
		 * L​o​a​d​i​n​g​ ​p​r​o​j​e​c​t​s​.​.​.
		 */
		loading: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​l​o​a​d​ ​p​r​o​j​e​c​t​s
		 */
		loadError: string
		/**
		 * C​r​e​a​t​e​ ​p​r​o​j​e​c​t
		 */
		create: string
		/**
		 * P​r​o​j​e​c​t​ ​c​r​e​a​t​e​d
		 */
		created: string
		/**
		 * P​r​o​j​e​c​t​ ​"​{​n​a​m​e​}​"​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 * @param {string} name
		 */
		createdMessage: RequiredParams<'name'>
		/**
		 * E​r​r​o​r​ ​c​r​e​a​t​i​n​g​ ​p​r​o​j​e​c​t
		 */
		createError: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​r​o​j​e​c​t​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		createErrorMessage: string
		/**
		 * O​p​e​n​ ​p​r​o​j​e​c​t
		 */
		open: string
		/**
		 * P​i​n
		 */
		pin: string
		/**
		 * U​n​p​i​n
		 */
		unpin: string
		/**
		 * P​r​o​j​e​c​t​ ​p​i​n​n​e​d
		 */
		pinned: string
		/**
		 * D​e​l​e​t​e​ ​p​r​o​j​e​c​t
		 */
		'delete': string
		/**
		 * L​e​a​v​e​ ​p​r​o​j​e​c​t
		 */
		leave: string
		/**
		 * P​r​o​j​e​c​t​ ​m​e​n​u
		 */
		menu: string
		role: {
			/**
			 * O​w​n​e​r
			 */
			owner: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​t​o​r
			 */
			admin: string
			/**
			 * E​d​i​t​o​r
			 */
			editor: string
			/**
			 * V​i​e​w​e​r
			 */
			viewer: string
		}
		/**
		 * {​c​o​u​n​t​}​ ​u​n​r​e​a​d​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
		 * @param {number} count
		 */
		notifications: RequiredParams<'count'>
	}
	actions: {
		'delete': {
			/**
			 * D​e​l​e​t​e​ ​p​r​o​j​e​c​t
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​"​{​n​a​m​e​}​"​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
			 * @param {string} name
			 */
			message: RequiredParams<'name'>
			/**
			 * D​e​l​e​t​e
			 */
			confirm: string
		}
		leave: {
			/**
			 * L​e​a​v​e​ ​p​r​o​j​e​c​t
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​e​a​v​e​ ​t​h​e​ ​p​r​o​j​e​c​t​ ​"​{​n​a​m​e​}​"​?​ ​Y​o​u​ ​w​i​l​l​ ​l​o​s​e​ ​a​c​c​e​s​s​ ​t​o​ ​t​h​e​ ​p​r​o​j​e​c​t​.
			 * @param {string} name
			 */
			message: RequiredParams<'name'>
			/**
			 * L​e​a​v​e
			 */
			confirm: string
		}
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
	}
	forms: {
		/**
		 * P​r​o​j​e​c​t​ ​n​a​m​e
		 */
		projectName: string
		/**
		 * P​r​o​j​e​c​t​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		projectDescription: string
		/**
		 * V​i​s​i​b​i​l​i​t​y
		 */
		visibility: string
		/**
		 * T​a​g​s
		 */
		tags: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
	}
	icons: {
		/**
		 * U​p​l​o​a​d​ ​i​c​o​n​s
		 */
		upload: string
		/**
		 * D​e​l​e​t​e​ ​i​c​o​n
		 */
		'delete': string
		/**
		 * E​d​i​t​ ​i​c​o​n
		 */
		edit: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
		/**
		 * S​h​a​r​e
		 */
		share: string
		/**
		 * C​o​p​y
		 */
		copy: string
	}
	'export': {
		/**
		 * E​x​p​o​r​t
		 */
		title: string
		/**
		 * E​x​p​o​r​t​ ​f​o​r​m​a​t​s
		 */
		formats: string
		/**
		 * D​o​w​n​l​o​a​d
		 */
		download: string
	}
	languages: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * S​p​a​n​i​s​h
		 */
		es: string
		/**
		 * F​r​e​n​c​h
		 */
		fr: string
		/**
		 * G​e​r​m​a​n
		 */
		de: string
		/**
		 * P​o​r​t​u​g​u​e​s​e
		 */
		pt: string
		/**
		 * R​u​s​s​i​a​n
		 */
		ru: string
	}
	settings: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		title: string
		appearance: {
			/**
			 * A​p​p​e​a​r​a​n​c​e
			 */
			title: string
			language: {
				/**
				 * I​n​t​e​r​f​a​c​e​ ​L​a​n​g​u​a​g​e
				 */
				title: string
				/**
				 * C​h​o​o​s​e​ ​t​h​e​ ​l​a​n​g​u​a​g​e​ ​f​o​r​ ​d​i​s​p​l​a​y​i​n​g​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​n​t​e​r​f​a​c​e
				 */
				description: string
			}
		}
		account: {
			/**
			 * A​c​c​o​u​n​t
			 */
			title: string
			/**
			 * U​s​e​r
			 */
			user: string
			signOut: {
				/**
				 * S​i​g​n​ ​o​u​t​ ​f​r​o​m​ ​a​c​c​o​u​n​t
				 */
				title: string
				/**
				 * E​n​d​ ​c​u​r​r​e​n​t​ ​s​e​s​s​i​o​n​ ​a​n​d​ ​r​e​t​u​r​n​ ​t​o​ ​l​o​g​i​n​ ​s​c​r​e​e​n
				 */
				description: string
				/**
				 * S​i​g​n​ ​o​u​t
				 */
				button: string
			}
		}
		about: {
			/**
			 * A​b​o​u​t
			 */
			title: string
			/**
			 * F​o​x​i​c
			 */
			appName: string
			/**
			 * I​c​o​n​ ​f​o​n​t​ ​g​e​n​e​r​a​t​o​r​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​s
			 */
			appDescription: string
			/**
			 * V​e​r​s​i​o​n
			 */
			version: string
		}
	}
	common: {
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		loading: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * W​a​r​n​i​n​g
		 */
		warning: string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n
		 */
		info: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * F​i​l​t​e​r
		 */
		filter: string
		/**
		 * S​o​r​t
		 */
		sort: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * H​e​l​p
		 */
		help: string
		/**
		 * M​o​r​e
		 */
		more: string
		/**
		 * T​r​y​ ​a​g​a​i​n
		 */
		retry: string
	}
	home: {
		/**
		 * F​o​x​i​c
		 */
		appTitle: string
		/**
		 * I​c​o​n​ ​f​o​n​t​ ​g​e​n​e​r​a​t​o​r
		 */
		appDescription: string
		/**
		 * M​y​ ​P​r​o​j​e​c​t​s
		 */
		myProjects: string
		/**
		 * {​c​o​u​n​t​}​ ​p​r​o​j​e​c​t
		 * @param {number} count
		 */
		projectsCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​p​r​o​j​e​c​t​s
		 * @param {number} count
		 */
		projectsCountMany: RequiredParams<'count'>
		/**
		 * U​s​e​r​ ​m​e​n​u
		 */
		userMenu: string
		/**
		 * C​u​r​r​e​n​t​ ​u​s​e​r​:​ ​{​u​s​e​r​}
		 * @param {string} user
		 */
		currentUser: RequiredParams<'user'>
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g​s
		 */
		openSettings: string
	}
	pwa: {
		/**
		 * S​h​o​w​ ​P​r​o​g​r​e​s​s​i​v​e​ ​W​e​b​ ​A​p​p​ ​i​n​f​o​r​m​a​t​i​o​n
		 */
		info: string
		/**
		 * P​W​A​ ​S​t​a​t​u​s
		 */
		status: string
		/**
		 * P​W​A​ ​i​n​s​t​a​l​l​e​d
		 */
		installed: string
		/**
		 * S​e​r​v​i​c​e​ ​W​o​r​k​e​r
		 */
		serviceWorker: string
		/**
		 * O​n​l​i​n​e
		 */
		online: string
		/**
		 * C​a​c​h​e
		 */
		cache: string
		/**
		 * P​W​A​ ​S​t​a​t​u​s​:
		 */
		statusAlert: string
	}
	tooltips: {
		/**
		 * U​s​e​r​ ​p​r​o​f​i​l​e
		 */
		userAvatar: string
		/**
		 * S​i​g​n​ ​o​u​t​ ​f​r​o​m​ ​a​c​c​o​u​n​t
		 */
		signOut: string
		/**
		 * C​r​e​a​t​e​ ​n​e​w​ ​p​r​o​j​e​c​t
		 */
		createProject: string
		/**
		 * O​p​e​n​ ​p​r​o​j​e​c​t
		 */
		openProject: string
		/**
		 * P​i​n​ ​p​r​o​j​e​c​t
		 */
		pinProject: string
		/**
		 * U​n​p​i​n​ ​p​r​o​j​e​c​t
		 */
		unpinProject: string
		/**
		 * D​e​l​e​t​e​ ​p​r​o​j​e​c​t
		 */
		deleteProject: string
		/**
		 * L​e​a​v​e​ ​p​r​o​j​e​c​t
		 */
		leaveProject: string
		/**
		 * P​r​o​j​e​c​t​ ​m​e​n​u
		 */
		projectMenu: string
		/**
		 * U​p​l​o​a​d​ ​n​e​w​ ​i​c​o​n​s
		 */
		uploadIcons: string
		/**
		 * D​e​l​e​t​e​ ​i​c​o​n
		 */
		deleteIcon: string
		/**
		 * E​d​i​t​ ​i​c​o​n
		 */
		editIcon: string
		/**
		 * D​o​w​n​l​o​a​d​ ​i​c​o​n
		 */
		downloadIcon: string
		/**
		 * C​o​p​y​ ​i​c​o​n
		 */
		copyIcon: string
		/**
		 * E​x​p​o​r​t​ ​p​r​o​j​e​c​t
		 */
		exportProject: string
		/**
		 * D​o​w​n​l​o​a​d​ ​f​o​n​t
		 */
		downloadFont: string
		/**
		 * C​o​p​y​ ​C​S​S​ ​c​o​d​e
		 */
		copyCSS: string
		/**
		 * G​o​ ​t​o​ ​h​o​m​e​ ​p​a​g​e
		 */
		goHome: string
		/**
		 * G​o​ ​b​a​c​k
		 */
		goBack: string
		/**
		 * O​p​e​n​ ​s​e​t​t​i​n​g​s
		 */
		openSettings: string
		/**
		 * T​o​g​g​l​e​ ​t​h​e​m​e
		 */
		toggleTheme: string
		/**
		 * S​e​a​r​c​h​ ​p​r​o​j​e​c​t​s​ ​a​n​d​ ​i​c​o​n​s
		 */
		search: string
		/**
		 * F​i​l​t​e​r​ ​r​e​s​u​l​t​s
		 */
		filter: string
		/**
		 * S​o​r​t
		 */
		sort: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * H​e​l​p​ ​a​n​d​ ​s​u​p​p​o​r​t
		 */
		help: string
		/**
		 * M​o​r​e​ ​a​c​t​i​o​n​s
		 */
		more: string
	}
	a11y: {
		/**
		 * S​k​i​p​ ​t​o​ ​c​o​n​t​e​n​t
		 */
		skipToContent: string
		/**
		 * M​a​i​n​ ​c​o​n​t​e​n​t
		 */
		mainContent: string
		/**
		 * N​a​v​i​g​a​t​i​o​n
		 */
		navigation: string
		/**
		 * F​o​x​i​c​ ​-​ ​I​c​o​n​ ​f​o​n​t​ ​g​e​n​e​r​a​t​o​r
		 */
		applicationLandmark: string
		/**
		 * P​r​o​j​e​c​t​s​ ​g​r​i​d
		 */
		projectGrid: string
		/**
		 * Y​o​u​r​ ​r​o​l​e​ ​i​n​ ​p​r​o​j​e​c​t​:​ ​{​r​o​l​e​}
		 * @param {string} role
		 */
		projectRole: RequiredParams<'role'>
		/**
		 * L​o​a​d​i​n​g​ ​p​r​o​j​e​c​t​s
		 */
		loadingProjects: string
		/**
		 * N​o​ ​p​r​o​j​e​c​t​s​ ​a​v​a​i​l​a​b​l​e
		 */
		emptyProjects: string
		/**
		 * M​e​n​u​ ​e​x​p​a​n​d​e​d
		 */
		menuExpanded: string
		/**
		 * M​e​n​u​ ​c​o​l​l​a​p​s​e​d
		 */
		menuCollapsed: string
	}
	footer: {
		/**
		 * M​a​d​e​ ​b​y
		 */
		madeBy: string
		/**
		 * V​e​r​s​i​o​n
		 */
		version: string
	}
	errors: {
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
		 */
		generic: string
		/**
		 * N​e​t​w​o​r​k​ ​e​r​r​o​r
		 */
		network: string
		/**
		 * U​n​a​u​t​h​o​r​i​z​e​d
		 */
		unauthorized: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		notFound: string
		/**
		 * P​r​o​j​e​c​t​ ​n​o​t​ ​f​o​u​n​d
		 */
		projectNotFound: string
		/**
		 * I​n​s​u​f​f​i​c​i​e​n​t​ ​p​e​r​m​i​s​s​i​o​n​s
		 */
		insufficientPermissions: string
		/**
		 * O​n​l​y​ ​t​h​e​ ​o​w​n​e​r​ ​c​a​n​ ​d​e​l​e​t​e​ ​t​h​e​ ​p​r​o​j​e​c​t
		 */
		onlyOwnerCanDelete: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Aplication title
		 */
		title: () => LocalizedString
		/**
		 * Example app with i18n support
		 */
		description: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
	}
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Projects
		 */
		projects: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * User menu
		 */
		userMenu: () => LocalizedString
	}
	auth: {
		/**
		 * Sign in with Google
		 */
		loginWithGoogle: () => LocalizedString
		/**
		 * Sign out
		 */
		logout: () => LocalizedString
		/**
		 * Current user: {user}
		 */
		currentUser: (arg: { user: string }) => LocalizedString
		/**
		 * Sign out from account
		 */
		signOut: () => LocalizedString
	}
	projects: {
		/**
		 * My Projects
		 */
		title: () => LocalizedString
		/**
		 * {count} projects
		 */
		count: (arg: { count: unknown }) => LocalizedString
		empty: {
			/**
			 * You don't have any projects yet
			 */
			title: () => LocalizedString
			/**
			 * Create your first project to work with icons
			 */
			description: () => LocalizedString
			/**
			 * Create first project
			 */
			createFirst: () => LocalizedString
		}
		/**
		 * Loading projects...
		 */
		loading: () => LocalizedString
		/**
		 * Failed to load projects
		 */
		loadError: () => LocalizedString
		/**
		 * Create project
		 */
		create: () => LocalizedString
		/**
		 * Project created
		 */
		created: () => LocalizedString
		/**
		 * Project "{name}" created successfully
		 */
		createdMessage: (arg: { name: string }) => LocalizedString
		/**
		 * Error creating project
		 */
		createError: () => LocalizedString
		/**
		 * Failed to create project. Please try again.
		 */
		createErrorMessage: () => LocalizedString
		/**
		 * Open project
		 */
		open: () => LocalizedString
		/**
		 * Pin
		 */
		pin: () => LocalizedString
		/**
		 * Unpin
		 */
		unpin: () => LocalizedString
		/**
		 * Project pinned
		 */
		pinned: () => LocalizedString
		/**
		 * Delete project
		 */
		'delete': () => LocalizedString
		/**
		 * Leave project
		 */
		leave: () => LocalizedString
		/**
		 * Project menu
		 */
		menu: () => LocalizedString
		role: {
			/**
			 * Owner
			 */
			owner: () => LocalizedString
			/**
			 * Administrator
			 */
			admin: () => LocalizedString
			/**
			 * Editor
			 */
			editor: () => LocalizedString
			/**
			 * Viewer
			 */
			viewer: () => LocalizedString
		}
		/**
		 * {count} unread notifications
		 */
		notifications: (arg: { count: number }) => LocalizedString
	}
	actions: {
		'delete': {
			/**
			 * Delete project
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to delete the project "{name}"? This action cannot be undone.
			 */
			message: (arg: { name: string }) => LocalizedString
			/**
			 * Delete
			 */
			confirm: () => LocalizedString
		}
		leave: {
			/**
			 * Leave project
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to leave the project "{name}"? You will lose access to the project.
			 */
			message: (arg: { name: string }) => LocalizedString
			/**
			 * Leave
			 */
			confirm: () => LocalizedString
		}
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
	}
	forms: {
		/**
		 * Project name
		 */
		projectName: () => LocalizedString
		/**
		 * Project description
		 */
		projectDescription: () => LocalizedString
		/**
		 * Visibility
		 */
		visibility: () => LocalizedString
		/**
		 * Tags
		 */
		tags: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
	}
	icons: {
		/**
		 * Upload icons
		 */
		upload: () => LocalizedString
		/**
		 * Delete icon
		 */
		'delete': () => LocalizedString
		/**
		 * Edit icon
		 */
		edit: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
		/**
		 * Share
		 */
		share: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
	}
	'export': {
		/**
		 * Export
		 */
		title: () => LocalizedString
		/**
		 * Export formats
		 */
		formats: () => LocalizedString
		/**
		 * Download
		 */
		download: () => LocalizedString
	}
	languages: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Spanish
		 */
		es: () => LocalizedString
		/**
		 * French
		 */
		fr: () => LocalizedString
		/**
		 * German
		 */
		de: () => LocalizedString
		/**
		 * Portuguese
		 */
		pt: () => LocalizedString
		/**
		 * Russian
		 */
		ru: () => LocalizedString
	}
	settings: {
		/**
		 * Settings
		 */
		title: () => LocalizedString
		appearance: {
			/**
			 * Appearance
			 */
			title: () => LocalizedString
			language: {
				/**
				 * Interface Language
				 */
				title: () => LocalizedString
				/**
				 * Choose the language for displaying the application interface
				 */
				description: () => LocalizedString
			}
		}
		account: {
			/**
			 * Account
			 */
			title: () => LocalizedString
			/**
			 * User
			 */
			user: () => LocalizedString
			signOut: {
				/**
				 * Sign out from account
				 */
				title: () => LocalizedString
				/**
				 * End current session and return to login screen
				 */
				description: () => LocalizedString
				/**
				 * Sign out
				 */
				button: () => LocalizedString
			}
		}
		about: {
			/**
			 * About
			 */
			title: () => LocalizedString
			/**
			 * Foxic
			 */
			appName: () => LocalizedString
			/**
			 * Icon font generator for your projects
			 */
			appDescription: () => LocalizedString
			/**
			 * Version
			 */
			version: () => LocalizedString
		}
	}
	common: {
		/**
		 * Loading...
		 */
		loading: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * Warning
		 */
		warning: () => LocalizedString
		/**
		 * Information
		 */
		info: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Filter
		 */
		filter: () => LocalizedString
		/**
		 * Sort
		 */
		sort: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Help
		 */
		help: () => LocalizedString
		/**
		 * More
		 */
		more: () => LocalizedString
		/**
		 * Try again
		 */
		retry: () => LocalizedString
	}
	home: {
		/**
		 * Foxic
		 */
		appTitle: () => LocalizedString
		/**
		 * Icon font generator
		 */
		appDescription: () => LocalizedString
		/**
		 * My Projects
		 */
		myProjects: () => LocalizedString
		/**
		 * {count} project
		 */
		projectsCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} projects
		 */
		projectsCountMany: (arg: { count: number }) => LocalizedString
		/**
		 * User menu
		 */
		userMenu: () => LocalizedString
		/**
		 * Current user: {user}
		 */
		currentUser: (arg: { user: string }) => LocalizedString
		/**
		 * Open settings
		 */
		openSettings: () => LocalizedString
	}
	pwa: {
		/**
		 * Show Progressive Web App information
		 */
		info: () => LocalizedString
		/**
		 * PWA Status
		 */
		status: () => LocalizedString
		/**
		 * PWA installed
		 */
		installed: () => LocalizedString
		/**
		 * Service Worker
		 */
		serviceWorker: () => LocalizedString
		/**
		 * Online
		 */
		online: () => LocalizedString
		/**
		 * Cache
		 */
		cache: () => LocalizedString
		/**
		 * PWA Status:
		 */
		statusAlert: () => LocalizedString
	}
	tooltips: {
		/**
		 * User profile
		 */
		userAvatar: () => LocalizedString
		/**
		 * Sign out from account
		 */
		signOut: () => LocalizedString
		/**
		 * Create new project
		 */
		createProject: () => LocalizedString
		/**
		 * Open project
		 */
		openProject: () => LocalizedString
		/**
		 * Pin project
		 */
		pinProject: () => LocalizedString
		/**
		 * Unpin project
		 */
		unpinProject: () => LocalizedString
		/**
		 * Delete project
		 */
		deleteProject: () => LocalizedString
		/**
		 * Leave project
		 */
		leaveProject: () => LocalizedString
		/**
		 * Project menu
		 */
		projectMenu: () => LocalizedString
		/**
		 * Upload new icons
		 */
		uploadIcons: () => LocalizedString
		/**
		 * Delete icon
		 */
		deleteIcon: () => LocalizedString
		/**
		 * Edit icon
		 */
		editIcon: () => LocalizedString
		/**
		 * Download icon
		 */
		downloadIcon: () => LocalizedString
		/**
		 * Copy icon
		 */
		copyIcon: () => LocalizedString
		/**
		 * Export project
		 */
		exportProject: () => LocalizedString
		/**
		 * Download font
		 */
		downloadFont: () => LocalizedString
		/**
		 * Copy CSS code
		 */
		copyCSS: () => LocalizedString
		/**
		 * Go to home page
		 */
		goHome: () => LocalizedString
		/**
		 * Go back
		 */
		goBack: () => LocalizedString
		/**
		 * Open settings
		 */
		openSettings: () => LocalizedString
		/**
		 * Toggle theme
		 */
		toggleTheme: () => LocalizedString
		/**
		 * Search projects and icons
		 */
		search: () => LocalizedString
		/**
		 * Filter results
		 */
		filter: () => LocalizedString
		/**
		 * Sort
		 */
		sort: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Help and support
		 */
		help: () => LocalizedString
		/**
		 * More actions
		 */
		more: () => LocalizedString
	}
	a11y: {
		/**
		 * Skip to content
		 */
		skipToContent: () => LocalizedString
		/**
		 * Main content
		 */
		mainContent: () => LocalizedString
		/**
		 * Navigation
		 */
		navigation: () => LocalizedString
		/**
		 * Foxic - Icon font generator
		 */
		applicationLandmark: () => LocalizedString
		/**
		 * Projects grid
		 */
		projectGrid: () => LocalizedString
		/**
		 * Your role in project: {role}
		 */
		projectRole: (arg: { role: string }) => LocalizedString
		/**
		 * Loading projects
		 */
		loadingProjects: () => LocalizedString
		/**
		 * No projects available
		 */
		emptyProjects: () => LocalizedString
		/**
		 * Menu expanded
		 */
		menuExpanded: () => LocalizedString
		/**
		 * Menu collapsed
		 */
		menuCollapsed: () => LocalizedString
	}
	footer: {
		/**
		 * Made by
		 */
		madeBy: () => LocalizedString
		/**
		 * Version
		 */
		version: () => LocalizedString
	}
	errors: {
		/**
		 * An error occurred
		 */
		generic: () => LocalizedString
		/**
		 * Network error
		 */
		network: () => LocalizedString
		/**
		 * Unauthorized
		 */
		unauthorized: () => LocalizedString
		/**
		 * Not found
		 */
		notFound: () => LocalizedString
		/**
		 * Project not found
		 */
		projectNotFound: () => LocalizedString
		/**
		 * Insufficient permissions
		 */
		insufficientPermissions: () => LocalizedString
		/**
		 * Only the owner can delete the project
		 */
		onlyOwnerCanDelete: () => LocalizedString
	}
}

export type Formatters = {}
