name: 'Checkout'

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/**.yaml'
      - '.github/**.yml'
      - 'bin/**.js'
      - 'test/**.js'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    name: 'Checkout'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      pub-cache-name: pub
      threshold: 50
    timeout-minutes: 15
    concurrency:
      group: checkout-${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: 🚂 Get latest code
        id: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            .npmignore
            package.json
            bin
            example
            CHANGELOG.md

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run Tests
        run: npm test
        if: runner.os != 'Linux'

      # - name: Lint Code
      #   run: |
      #     npm run lint
