name: 'Publish to npm'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]*'
      - 'v[0-9]+.[0-9]+.[0-9]-*'
  #release:
  #  types:
  #    - created

jobs:
  deploy:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    timeout-minutes: 15
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        id: install
        run: |
          npm install
          npm install -g sheety-localization

      - name: Publish to npm
        id: publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
